### ISSUE TITLE
Error: Could not load plugin

### ISSUE THREAD

**Issue by tanabi** [raymondbutcher/terraform-aws-lambda-builder#16]
Hey there;

I'm a bit of a terraform n00b so apologies if this is something silly.  However, when I try to run terraform plan I get:

```
Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/archive" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/archive
```

I am running terraform init before running plan and it says:

```
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Then I set a workspace 'test' and try to run plan.

Here's my configuration block in tf -- the AWS role is being created and I can see it.

```
module "lambda_function" {
    source = "raymondbutcher/lambda-builder/aws"
    version = "1.2.0"

    # Lambda configuration
    function_name = "redirects-${var.environment}"
    role          = aws_iam_role.lambda_redirect_role.arn
    timeout       = 5
    memory_size   = 512
    description   = "redacted"
    filename      = "redirect.zip"
    runtime       = "nodejs14.x"
    region        = "us-east-1"
    handler       = "index.handler"

    # Packager configuration
    build_mode = "FILENAME"
    source_dir = "${path.module}/../redirect"
}
```

I have also tried to use your GIT hub as a source instead of from the repository.

Our terraform version is 2.0.0 and our process currently works if I don't try to use your module.  Thanks!

**Comment by raymondbutcher** [comment]
Hi @tanabi.

I've not seen this issue before but [this article](https://support.hashicorp.com/hc/en-us/articles/360052933774-Plugin-reinitialization-error-after-upgrade-to-Terraform-0-13) looks similar. I would try deleting the `.terraform` directory and/or `.terraform.lock.hcl` file as that can sometimes help with provider issues. If that doesn't work, maybe the article's instructions will help (I haven't had this issue, and haven't used the commands in the article before, so I don't really know).

Other observations:
* I don't think (from memory and a quick look through the code) that this module uses the archive provider (`registry.terraform.io/hashicorp/archive`) so unless I've missed something, it can't be this module that is causing this error. Try commenting out this module and see if it still breaks?
* There is no such thing as Terraform version 2.0.0.
* There is no `region` variable for this module.

It's been a couple of days since you posted this issue - did you figure it out?

Cheers.

**Comment by tanabi** [comment]
Thank you so much for your detailed message and putting up with my newbiness.  I think the archive is referenced by your own archive module which is used by this one (https://github.com/raymondbutcher/terraform-archive-stable I think) but I could be wrong.  Our deployment definitely works with the module commented out.

I haven't figured it out, but, I'm going to switch to another known-working but less elegant approach that we're using elsewhere to deploy lambdas.  I don't think I know this stuff well enough to try and get creative with it and I don't want to take up more of your time, thank you so much for helping me.
